# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = "0.3.5.dev39+gb4ffe86.d20221012"
__version_tuple__ = version_tuple = (0, 3, 5, "dev39", "gb4ffe86.d20221012")
