# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = "0.3.5.dev22+g1c6c47d"
__version_tuple__ = version_tuple = (0, 3, 5, "dev22", "g1c6c47d")
